export const INIT_MOVE = 'INIT_MOVE'
export const UPDATE_MOVES = 'UPDATE_MOVES'
export const CHANGE_PLAYER = 'CHANGE_PLAYER'
export const NEW_GAME = 'NEW_GAME'
export const OVER_GAME = 'OVER_GAME'
export const ADD_MOVE = 'ADD_MOVE'
export const INCREMENT_LEVEL = 'INCREMENT_LEVEL'
export const UPDATE_SPEED = 'UPDATE_SPEED'